/**
 * Emits the machine catalog and full-ingest text, and copies the offline
 * snapshot the MCP package bundles.
 *
 *   public/registry-meta.json      — the machine catalog (served + snapshotted)
 *   public/llms-full.txt           — full-ingest reference (served + snapshotted)
 *   .generated/agents-rules.ts     — AGENTS.md text for the force-static route
 *   packages/mcp/snapshot/*        — committed offline copy for the MCP server
 *
 * Run via: pnpm generate (or tsx scripts/build-machine-meta.ts)
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import { buildLlmsFull, buildMachineMeta } from "../content/machine-meta";

const ROOT = path.resolve(import.meta.dirname, "..");
const PUBLIC_DIR = path.join(ROOT, "public");
const GENERATED_DIR = path.join(ROOT, ".generated");
const SNAPSHOT_DIR = path.join(ROOT, "packages", "mcp", "snapshot");
const AGENTS_RULES_SRC = path.join(ROOT, "registry", "files", "agents-rules.md");

async function main() {
  const agentsRules = await readFile(AGENTS_RULES_SRC, "utf8");
  const meta = buildMachineMeta();
  const metaJson = `${JSON.stringify(meta, null, 2)}\n`;
  const llmsFull = buildLlmsFull(agentsRules);

  await mkdir(PUBLIC_DIR, { recursive: true });
  await mkdir(GENERATED_DIR, { recursive: true });
  await mkdir(SNAPSHOT_DIR, { recursive: true });

  // Served by the site. (registry-meta.json is a static asset; /llms-full.txt
  // is a force-static route, so it must NOT also exist under public/.)
  await writeFile(path.join(PUBLIC_DIR, "registry-meta.json"), metaJson);

  // Inlined by the force-static /llms-full.txt route (no runtime fs).
  const banner =
    "// Generated by scripts/build-machine-meta.ts — do not edit by hand.\n";
  await writeFile(
    path.join(GENERATED_DIR, "agents-rules.ts"),
    `${banner}export const agentsRules = ${JSON.stringify(agentsRules)};\n`,
  );

  // Committed offline snapshot the MCP package bundles.
  await writeFile(path.join(SNAPSHOT_DIR, "registry-meta.json"), metaJson);
  await writeFile(path.join(SNAPSHOT_DIR, "llms-full.txt"), llmsFull);
  await writeFile(path.join(SNAPSHOT_DIR, "agents-rules.md"), agentsRules);

  console.log(
    `machine-meta: ${meta.items.length} item(s) → registry-meta.json, llms-full.txt, snapshot/`,
  );
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
