/**
 * Snapshots every registry/ source file (components, blocks, hooks, libs,
 * demos) into .generated/sources.ts. Docs pages statically import that map,
 * so the Code/Usage tabs always show the exact bytes that ship — and no
 * runtime fs access is needed on the server.
 */
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");
const REGISTRY_DIR = path.join(ROOT, "registry");
const OUT_DIR = path.join(ROOT, ".generated");

async function collectFiles(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true }).catch(() => []);
  const files: string[] = [];
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await collectFiles(full)));
    } else if (/\.(ts|tsx|css)$/.test(entry.name)) {
      files.push(full);
    }
  }
  return files;
}

async function main() {
  const files = await collectFiles(REGISTRY_DIR);
  const sources: Record<string, string> = {};

  for (const file of files.sort()) {
    const repoRelative = path.relative(ROOT, file).split(path.sep).join("/");
    sources[repoRelative] = await readFile(file, "utf8");
  }

  await mkdir(OUT_DIR, { recursive: true });
  const banner =
    "// Generated by scripts/extract-sources.ts — do not edit by hand.\n";
  const body = `export const sources: Record<string, string> = ${JSON.stringify(
    sources,
    null,
    2,
  )};\n`;
  await writeFile(path.join(OUT_DIR, "sources.ts"), banner + body);

  console.log(`sources: ${files.length} file(s) → .generated/sources.ts`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
